"""
Automatically generated file from 
C:/Users/lwiniwar/.qgis2/python/plugins\qpals-nightly\qpals\resources\get_attribute_types.py 
on 2017-11-16 
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
""" 
odm_predef_attributes = {
    'Amplitude': 'float',
    'Attribute': 'unsignedByte',
    'BeamVectorX': 'float',
    'BeamVectorY': 'float',
    'BeamVectorZ': 'float',
    'Blue': 'unsignedShort',
    'ChannelDesc': 'unsignedByte',
    'Classification': 'unsignedByte',
    'ClassificationFlags': 'unsignedByte',
    'Confidence': 'unsignedByte',
    'ConstrainedFlag': 'boolean',
    'CrossSection': 'float',
    'CumulativeDistance': 'float',
    'CurveParam': 'float',
    'CustomClassId': 'unsignedByte',
    'EchoNumber': 'unsignedByte',
    'EchoRatio': 'float',
    'EchoWidth': 'float',
    'EchoWidthNormalised': 'float',
    'EdgeOfFlightLine': 'boolean',
    'Estimator': 'unsignedByte',
    'FaceId': 'unsignedInt',
    'FileId': 'unsignedShort',
    'GPSTime': 'double',
    'Green': 'unsignedShort',
    'Id': 'int64',
    'InfraRed': 'unsignedShort',
    'LASExtensions': 'string',
    'LayerId': 'unsignedShort',
    'MarkedFlag': 'boolean',
    'MaxCurvature': 'float',
    'MaxCurvatureDirection': 'float',
    'MinCurvature': 'float',
    'NormalEigenvalue1': 'float',
    'NormalEigenvalue2': 'float',
    'NormalEigenvalue3': 'float',
    'NormalEstimationMethod': 'unsignedByte',
    'NormalLeftX': 'float',
    'NormalLeftY': 'float',
    'NormalLeftZ': 'float',
    'NormalPlaneOffset': 'float',
    'NormalPtsGiven': 'unsignedByte',
    'NormalPtsUsed': 'unsignedByte',
    'NormalRightX': 'float',
    'NormalRightY': 'float',
    'NormalRightZ': 'float',
    'NormalSigma0': 'float',
    'NormalX': 'float',
    'NormalY': 'float',
    'NormalZ': 'float',
    'NormalizedZ': 'float',
    'NrOfEchos': 'unsignedByte',
    'PitchAngle': 'float',
    'PointCode': 'string',
    'PointLabel': 'string',
    'PointSourceId': 'unsignedShort',
    'RGIndex': 'unsignedShort',
    'Range': 'float',
    'Red': 'unsignedShort',
    'Reflectance': 'float',
    'Residual': 'float',
    'RollAngle': 'float',
    'ScanAngle': 'float',
    'ScanDirection': 'boolean',
    'ScopSemantic': 'int',
    'SegmentID': 'unsignedInt',
    'SegmentPtsUsed': 'int',
    'SigmaNormalFit': 'float',
    'SigmaX': 'float',
    'SigmaY': 'float',
    'SigmaZ': 'float',
    'SpreadAngle': 'float',
    'StructNr': 'unsignedShort',
    'TangentSigmaX': 'float',
    'TangentSigmaY': 'float',
    'TangentSigmaZ': 'float',
    'TangentX': 'float',
    'TangentY': 'float',
    'TangentZ': 'float',
    'TiltAngle': 'float',
    'UltraViolet': 'unsignedShort',
    'UserData': 'unsignedByte',
    'VertexId': 'unsignedInt',
    'WaterDepth': 'float',
    'WinputCode': 'unsignedShort',
    'YawAngle': 'float',
}
odm_data_types = [
    'int',
    'unsignedInt',
    'byte',
    'unsignedByte',
    'short',
    'unsignedShort',
    'float',
    'double',
    'string',
    'int64',
    'char',
    'boolean',
]
