
odm_data_types=[
"64bit integer",
"integer",
"unsigned integer",
"short",
"unsigned short",
"byte",
"unsigned byte",
"boolean",
"float",
"double",
"string",
]

odm_predef_attributes = {
    "Amplitude": "float",
    "Attribute": "unsigned byte",
    "BeamVectorX": "float",
    "BeamVectorY": "float",
    "BeamVectorZ": "float",
    "Blue": "unsigned short",
    "ChannelDesc": "unsigned byte",
    "Classification": "unsigned byte",
    "ClassificationFlags": "unsigned byte",
    "Confidence": "unsigned byte",
    "ConstrainedFlag": "bool",
    "CrossSection": "float",
    "CumulativeDistance": "float",
    "CurveParam": "float",
    "CustomClassId": "unsigned byte",
    "EchoNumber": "unsigned byte",
    "EchoRatio": "float",
    "EchoWidth": "float",
    "EchoWidthNormalised": "float",
    "EdgeOfFlightLine": "bool",
    "Estimator": "unsigned byte",
    "FaceId": "unsigned integer",
    "FileId": "unsigned short",
    "GPSTime": "double",
    "Green": "unsigned short",
    "Id": "64bit integer",
    "InfraRed": "unsigned short",
    "LASExtensions": "string",
    "LayerId": "unsigned short",
    "MarkedFlag": "bool",
    "MaxCurvature": "float",
    "MaxCurvatureDirection": "float",
    "MinCurvature": "float",
    "NormalEigenvalue1": "float",
    "NormalEigenvalue2": "float",
    "NormalEigenvalue3": "float",
    "NormalEstimationMethod": "unsigned byte",
    "NormalLeftX": "float",
    "NormalLeftY": "float",
    "NormalLeftZ": "float",
    "NormalPlaneOffset": "float",
    "NormalPtsGiven": "unsigned byte",
    "NormalPtsUsed": "unsigned byte",
    "NormalRightX": "float",
    "NormalRightY": "float",
    "NormalRightZ": "float",
    "NormalSigma0": "float",
    "NormalX": "float",
    "NormalY": "float",
    "NormalZ": "float",
    "NormalizedZ": "float",
    "NrOfEchos": "unsigned byte",
    "PitchAngle": "float",
    "PointCode": "string",
    "PointLabel": "string",
    "PointSourceId": "unsigned short",
    "RGIndex": "unsigned short",
    "Range": "float",
    "Red": "unsigned short",
    "Reflectance": "float",
    "Residual": "float",
    "RollAngle": "float",
    "ScanAngle": "float",
    "ScanDirection": "bool",
    "ScopSemantic": "integer",
    "SegmentID": "unsigned integer",
    "SegmentPtsUsed": "integer",
    "SigmaNormalFit": "float",
    "SigmaX": "float",
    "SigmaY": "float",
    "SigmaZ": "float",
    "SpreadAngle": "float",
    "StructNr": "unsigned short",
    "TangentSigmaX": "float",
    "TangentSigmaY": "float",
    "TangentSigmaZ": "float",
    "TangentX": "float",
    "TangentY": "float",
    "TangentZ": "float",
    "TiltAngle": "float",
    "UltraViolet": "unsigned short",
    "UserData": "unsigned byte",
    "VertexId": "unsigned integer",
    "WaterDepth": "float",
    "WinputCode": "unsigned short",
    "YawAngle": "float",
}