"""
Automatically generated file from 
D:/swdvlp64_cmake/opals/qpals/plugin/pyqpals/resources/get_attribute_types.py 
on 2024-08-28 
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
""" 
odm_predef_attributes = {
    'Amplitude': 'float',
    'Attribute': 'uint8',
    'BeamVectorX': 'float',
    'BeamVectorY': 'float',
    'BeamVectorZ': 'float',
    'Blue': 'uint16',
    'ChannelDesc': 'uint8',
    'Classification': 'uint8',
    'ClassificationFlags': 'uint8',
    'Confidence': 'uint8',
    'ConstrainedFlag': 'bool',
    'CrossSection': 'float',
    'CumulativeDistance': 'float',
    'CurveParam': 'float',
    'CustomClassId': 'uint8',
    'EchoNumber': 'uint8',
    'EchoRatio': 'float',
    'EchoWidth': 'float',
    'EchoWidthNormalised': 'float',
    'EdgeOfFlightLine': 'bool',
    'Estimator': 'uint8',
    'FaceId': 'uint32',
    'FileId': 'uint16',
    'GPSTime': 'double',
    'Green': 'uint16',
    'Id': 'int64',
    'InfraRed': 'uint16',
    'KappaAngle': 'float',
    'LASExtensions': 'string',
    'LayerId': 'uint16',
    'MarkedFlag': 'bool',
    'MaxCurvature': 'float',
    'MaxCurvatureDirection': 'float',
    'MinCurvature': 'float',
    'NormalEigenvalue1': 'float',
    'NormalEigenvalue2': 'float',
    'NormalEigenvalue3': 'float',
    'NormalEstimationMethod': 'uint8',
    'NormalLeftX': 'float',
    'NormalLeftY': 'float',
    'NormalLeftZ': 'float',
    'NormalPlaneOffset': 'float',
    'NormalPtsGiven': 'uint8',
    'NormalPtsUsed': 'uint8',
    'NormalRightX': 'float',
    'NormalRightY': 'float',
    'NormalRightZ': 'float',
    'NormalSigma0': 'float',
    'NormalX': 'float',
    'NormalY': 'float',
    'NormalZ': 'float',
    'NormalizedZ': 'float',
    'NrOfEchos': 'uint8',
    'OmegaAngle': 'float',
    'PanAngle': 'float',
    'PhiAngle': 'float',
    'PitchAngle': 'float',
    'PointCode': 'string',
    'PointLabel': 'string',
    'PointSourceId': 'uint16',
    'RGIndex': 'uint16',
    'Range': 'float',
    'Red': 'uint16',
    'Reflectance': 'float',
    'Residual': 'float',
    'RollAngle': 'float',
    'ScanAngle': 'float',
    'ScanDirection': 'bool',
    'ScopSemantic': 'int32',
    'SegmentID': 'uint32',
    'SegmentPtsUsed': 'int32',
    'SigmaNormalFit': 'float',
    'SigmaX': 'float',
    'SigmaY': 'float',
    'SigmaZ': 'float',
    'SpreadAngle': 'float',
    'StructNr': 'uint16',
    'TangentSigmaX': 'float',
    'TangentSigmaY': 'float',
    'TangentSigmaZ': 'float',
    'TangentX': 'float',
    'TangentY': 'float',
    'TangentZ': 'float',
    'TiltAngle': 'float',
    'UltraViolet': 'uint16',
    'UserData': 'uint8',
    'VertexId': 'uint32',
    'WaterDepth': 'float',
    'WinputCode': 'uint16',
    'X0': 'double',
    'Y0': 'double',
    'YawAngle': 'float',
    'Z0': 'double',
}
odm_data_types = [
    'int32',
    'uint32',
    'int8',
    'uint8',
    'int16',
    'uint16',
    'float',
    'double',
    'string',
    'int64',
    'cstr',
    'bool',
]
